# Generated by Django 2.2 on 2019-04-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus_logic', '0002_library_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
